# Generated by Django 3.1.3 on 2020-11-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unanswered_questions', models.IntegerField()),
                ('asked_questions', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
